version: 2.1

jobs:
  build:
    parameters:
      node_version:
        description: "Node version to test."
        type: string
      update_npm:
        description: "Whether to update npm to at least npm 7.x"
        default: false
        type: boolean
    working_directory: ~/inversify-token
    docker:
      - image: circleci/node:<< parameters.node_version >>
    steps:
      - checkout
      - when:
          condition:
            equal: [true, << parameters.update_npm >>]
          steps:
            - run: npm install -g npm@7
      - run: npm install
      - run: npm test
  lint:
    working_directory: ~/inversify-token
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: npm install
      - run: npx commitlint --from origin/main --to HEAD
  deploy:
    working_directory: ~/inversify-token
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: npm install
      - run: npm run semantic-release

workflows:
  version: 2
  ci:
    jobs:
      - lint
      - build:
          name: dubnium
          node_version: "10"
          update_npm: true
      - build:
          name: erbium
          node_version: "12"
          update_npm: true
      - build:
          name: fermium
          node_version: "14"
          update_npm: true
      - build:
          name: gallium
          node_version: "16"
      - build:
          name: latest
          node_version: "latest"
      - deploy:
          requires:
            - lint
            - dubnium
            - erbium
            - gallium
            - latest
          filters:
            branches:
              only: main
